# Generated by Django 3.0.4 on 2020-03-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=64)),
                ('open_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('realtime_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
